### ISSUE TITLE
Unable To find typings for code-push

### ISSUE THREAD

**Issue by savanvadalia** [ksachdeva/ionic2-code-push-example#1]
Trying to use your sample as guide for implementing code-push in my app.

I followed your steps for installation but 
I am not able find CodePush module like this
import { CodePush} from 'ionic-native';

Do I need to install typings for code-push separately?
Where can i find the typings for code-push?

Any help will be greatly appreciated?

Regards,
Savan

**Comment by ksachdeva** [comment]
Hi Savan,

My pull request in ionic-native has still not been accepted and even after acceptance it will take time to get it included with the next release of ionic-native.

Here is what you need to do :

git clone https://github.com/ksachdeva/ionic-native
cd into ionic-native
npm install
npm run build
npm link

the go to the ionic2-code-push-example
and do this
npm link ionic-native

You are all set after that

**Comment by savanvadalia** [comment]
Hi Kapil,

Thank you for those steps it worked perfectly fine and I was able to do a proof of concept for the code-push plugin in my test project. 

I have never used npm link before. Still don't understand the mechanics of that.

But one thing I noticed after doing the npm link, it seems my all native modules get loaded from the link (ionic-native package provided by you) instead of the package provided by ionic. This makes me think that your ionic-native package could potentially be out of date from the ionic's one.

Any estimate time line when would your plugin could be made part of ionic-native module?

Is there a way to "unlink" the package, I couldn't find any CLI command like "unlink" in npm for un-linking?

Regards,
Savan

**Comment by ksachdeva** [comment]
Here is the idea behind "npm link".

Let's say that you are developing a node module and want to test it. The module has not been deployed yet at the npm registry (or it may be a private module that you do not intend to push in the registry). One approach is to install it from local directory (since npm 2.0 it is supported). However since the module is still in development any change you would make it in the module will require you to uninstall and re-install the module in your application.

"npm link" solves this problem by creating a symbolic link to your module. Nothing more than this. This way if you make a change to your module it is reflected in your application as well.

Command to unlink is - npm unlink ionic-native.

##

> > it seems my all native modules get loaded from the link (ionic-native package provided by 
> > you) instead of the package provided by ionic

Another approach to prevent this that you can take is to simply copy the "dist" folder from ionic-native (my version) and then copy it in your node_moduls/ionic-native.

> > Any estimate time line when would your plugin could be made part of ionic-native module?

No.

Here is the pull request : https://github.com/driftyco/ionic-native/pull/420

Regards
Kapil

**Comment by ksachdeva** [comment]
It is now part of ionic-native 1.3.18
